language: node_js
node_js: "14"

dist: xenial

addons:
  apt:
    packages:
    - libgconf-2-4

services:
  - docker

env:
  - img=existdb/existdb:latest
  - img=existdb/existdb:release
  - img=existdb/existdb:4.7.1

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: deploy
      env: img=existdb/existdb:release
      script: skip
      provider: releases
      api_key: $GH_TOKEN
      file_glob: true
      file: build/*
      skip_cleanup: true
      on:
        tags: true

before_install:
  - docker pull $img
  - docker create  --name exist-ci -p 8080:8080 $img

install:
  - npm ci
  - npm run build

before_script:
  - docker cp ./build/eXide-*.xar exist-ci:exist/autodeploy
  - docker start exist-ci
  # exist needs time
  - sleep 30

script:
  - docker ps
  - npm run cypress -- --record

notifications:
  email: false
  slack: exist-db:IXzUdqA0n11cnxaDz43ZQgdX
